sudo: false
language: c
cache:
  directories:
  - $HOME/.stack
addons:
  apt:
    packages:
      - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- travis_wait 30 stack setup
- travis_wait 60 stack install idris
script:
- cd $TRAVIS_BUILD_DIR; make test

